/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FontDescriptor {
  postscriptName?: string
  family?: string
  style?: string
  weight?: number
  width?: number
  italic?: boolean
  monospace?: boolean
}
export declare function allFamilies(): Promise<Array<string>>
export declare function getFamilyVariants(familyName: string): Promise<Array<FontDescriptor>>
